# -*- coding: utf-8 -*-
"""Código_Orden.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HRpYzn7yrpjp7AIKEOeqQ7QitOJwAIfT
"""

lista = [12,3,5,8,1]
cantidad = len(lista)

def ordenar(lista):
  for i in range(cantidad):
    for j in range(i+1,cantidad):
      if lista[i] > lista[j]:
        lista[i],lista[j] = lista[j],lista[i]
  return lista

print(ordenar(lista))